In [1]:
from transformers import XLNetTokenizer

In [2]:
text = 'I love this flavor! It\'s by far the best choice and my go-to whenever I go to the grocery store. \n I wish they would restock it more often though.'

In [4]:
tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')
word_tokens = tokenizer.tokenize(text)
print(word_tokens)

['▁I', '▁love', '▁this', '▁flavor', '!', '▁It', "'", 's', '▁by', '▁far', '▁the', '▁best', '▁choice', '▁and', '▁my', '▁go', '-', 'to', '▁whenever', '▁I', '▁go', '▁to', '▁the', '▁grocery', '▁store', '.', '▁I', '▁wish', '▁they', '▁would', '▁rest', 'ock', '▁it', '▁more', '▁often', '▁though', '.']


In [5]:
with open('../data/input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [6]:
text[:100]

'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou'

In [7]:
subtext = text.split(' ')[:100]
print(subtext)
for i, substring in enumerate(subtext):
    
    if '\n' in substring:
        chars = [c for c in substring]
        # print(chars)
        
        sindex = 0
        split_substring_list = []
        for j, char in enumerate(chars):
            
            if char == '\n':
                c_chars = ''.join(chars[sindex:j])
                if  c_chars != '':
                    split_substring_list.append(c_chars)
                    
                split_substring_list.append('\n')
                sindex = j + 1
                
        split_substring_list.append(''.join(chars[sindex:]))
        
        # print(split_substring_list)
        
        subtext[i] = split_substring_list
    else:
        subtext[i] = [substring]

print(subtext)

['First', 'Citizen:\nBefore', 'we', 'proceed', 'any', 'further,', 'hear', 'me', 'speak.\n\nAll:\nSpeak,', 'speak.\n\nFirst', 'Citizen:\nYou', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish?\n\nAll:\nResolved.', 'resolved.\n\nFirst', 'Citizen:\nFirst,', 'you', 'know', 'Caius', 'Marcius', 'is', 'chief', 'enemy', 'to', 'the', 'people.\n\nAll:\nWe', "know't,", 'we', "know't.\n\nFirst", 'Citizen:\nLet', 'us', 'kill', 'him,', 'and', "we'll", 'have', 'corn', 'at', 'our', 'own', "price.\nIs't", 'a', 'verdict?\n\nAll:\nNo', 'more', 'talking', "on't;", 'let', 'it', 'be', 'done:', 'away,', 'away!\n\nSecond', 'Citizen:\nOne', 'word,', 'good', 'citizens.\n\nFirst', 'Citizen:\nWe', 'are', 'accounted', 'poor', 'citizens,', 'the', 'patricians', 'good.\nWhat', 'authority', 'surfeits', 'on', 'would', 'relieve', 'us:', 'if', 'they\nwould', 'yield', 'us', 'but', 'the', 'superfluity,', 'while', 'it', 'were\nwholesome,', 'we', 'might', 'guess', 'they', 'relieved', 'us', 'humanely;\nb

In [8]:
subtext = [item for sublist in subtext for item in sublist]
print(subtext)

['First', 'Citizen:', '\n', 'Before', 'we', 'proceed', 'any', 'further,', 'hear', 'me', 'speak.', '\n', '\n', 'All:', '\n', 'Speak,', 'speak.', '\n', '\n', 'First', 'Citizen:', '\n', 'You', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish?', '\n', '\n', 'All:', '\n', 'Resolved.', 'resolved.', '\n', '\n', 'First', 'Citizen:', '\n', 'First,', 'you', 'know', 'Caius', 'Marcius', 'is', 'chief', 'enemy', 'to', 'the', 'people.', '\n', '\n', 'All:', '\n', 'We', "know't,", 'we', "know't.", '\n', '\n', 'First', 'Citizen:', '\n', 'Let', 'us', 'kill', 'him,', 'and', "we'll", 'have', 'corn', 'at', 'our', 'own', 'price.', '\n', "Is't", 'a', 'verdict?', '\n', '\n', 'All:', '\n', 'No', 'more', 'talking', "on't;", 'let', 'it', 'be', 'done:', 'away,', 'away!', '\n', '\n', 'Second', 'Citizen:', '\n', 'One', 'word,', 'good', 'citizens.', '\n', '\n', 'First', 'Citizen:', '\n', 'We', 'are', 'accounted', 'poor', 'citizens,', 'the', 'patricians', 'good.', '\n', 'What', 'authority', 'surf

In [9]:
for i, tokens in enumerate(subtext):
    if tokens == '\n':
        continue
    subtext[i] = tokenizer.tokenize(tokens)

print(subtext)

[['▁First'], ['▁', 'Citizen', ':'], '\n', ['▁Before'], ['▁we'], ['▁proceed'], ['▁any'], ['▁further', ','], ['▁hear'], ['▁me'], ['▁speak', '.'], '\n', '\n', ['▁All', ':'], '\n', ['▁', 'S', 'peak', ','], ['▁speak', '.'], '\n', '\n', ['▁First'], ['▁', 'Citizen', ':'], '\n', ['▁You'], ['▁are'], ['▁all'], ['▁resolved'], ['▁rather'], ['▁to'], ['▁die'], ['▁than'], ['▁to'], ['▁', 'fa', 'm', 'ish', '?'], '\n', '\n', ['▁All', ':'], '\n', ['▁Re', 'solv', 'ed', '.'], ['▁resolved', '.'], '\n', '\n', ['▁First'], ['▁', 'Citizen', ':'], '\n', ['▁First', ','], ['▁you'], ['▁know'], ['▁Cai', 'us'], ['▁Marc', 'ius'], ['▁is'], ['▁chief'], ['▁enemy'], ['▁to'], ['▁the'], ['▁people', '.'], '\n', '\n', ['▁All', ':'], '\n', ['▁We'], ['▁know', "'", 't', ','], ['▁we'], ['▁know', "'", 't', '.'], '\n', '\n', ['▁First'], ['▁', 'Citizen', ':'], '\n', ['▁Let'], ['▁us'], ['▁kill'], ['▁him', ','], ['▁and'], ['▁we', "'", 'll'], ['▁have'], ['▁corn'], ['▁at'], ['▁our'], ['▁own'], ['▁price', '.'], '\n', ['▁I', 's', "'", 't'

In [10]:
subtext = [item for sublist in subtext for item in sublist]
print(subtext)

['▁First', '▁', 'Citizen', ':', '\n', '▁Before', '▁we', '▁proceed', '▁any', '▁further', ',', '▁hear', '▁me', '▁speak', '.', '\n', '\n', '▁All', ':', '\n', '▁', 'S', 'peak', ',', '▁speak', '.', '\n', '\n', '▁First', '▁', 'Citizen', ':', '\n', '▁You', '▁are', '▁all', '▁resolved', '▁rather', '▁to', '▁die', '▁than', '▁to', '▁', 'fa', 'm', 'ish', '?', '\n', '\n', '▁All', ':', '\n', '▁Re', 'solv', 'ed', '.', '▁resolved', '.', '\n', '\n', '▁First', '▁', 'Citizen', ':', '\n', '▁First', ',', '▁you', '▁know', '▁Cai', 'us', '▁Marc', 'ius', '▁is', '▁chief', '▁enemy', '▁to', '▁the', '▁people', '.', '\n', '\n', '▁All', ':', '\n', '▁We', '▁know', "'", 't', ',', '▁we', '▁know', "'", 't', '.', '\n', '\n', '▁First', '▁', 'Citizen', ':', '\n', '▁Let', '▁us', '▁kill', '▁him', ',', '▁and', '▁we', "'", 'll', '▁have', '▁corn', '▁at', '▁our', '▁own', '▁price', '.', '\n', '▁I', 's', "'", 't', '▁a', '▁verdict', '?', '\n', '\n', '▁All', ':', '\n', '▁No', '▁more', '▁talking', '▁on', "'", 't', ';', '▁let', '▁it', 

In [11]:
flatten = lambda l: [item for sublist in l for item in sublist]

In [12]:
def split_newline(text):
    text = text.split(' ')
    
    for i, substring in enumerate(text):
        # detect substring containing the newline symbol '\n'
        if '\n' in substring:
            # split the substring by characters
            chars = [c for c in substring]
            
            sindex = 0
            split_substring_list = []
            for j, char in enumerate(chars):
                # When meets a newline, append all previous chars as a substring ([sindex:j])
                if char == '\n':
                    c_chars = ''.join(chars[sindex:j])
                    if  c_chars != '':
                        split_substring_list.append(c_chars)
                    # Then added the '\n'
                    split_substring_list.append('\n')
                    # Update the sindex
                    sindex = j + 1
            # Added the rest of all chars as a substring
            split_substring_list.append(''.join(chars[sindex:]))
            # Replace the original string by a list of string
            text[i] = split_substring_list
        else:
            # warp other items as a list
            text[i] = [substring]
    
    # Flatten the 
    return flatten(text)

def tokenization(text):
    for i, token in enumerate(text):
        # print(token)
        if token == '\n':
            continue
        text[i] = tokenizer.tokenize(token)
    
    return flatten(text)

In [13]:
subtext = text[:1000]
# print(subtext)
split_newline_subtext = split_newline(subtext)
print(split_newline_subtext)
tokenization_subtext = tokenization(split_newline_subtext)
print(tokenization_subtext)

['First', 'Citizen:', '\n', 'Before', 'we', 'proceed', 'any', 'further,', 'hear', 'me', 'speak.', '\n', '\n', 'All:', '\n', 'Speak,', 'speak.', '\n', '\n', 'First', 'Citizen:', '\n', 'You', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish?', '\n', '\n', 'All:', '\n', 'Resolved.', 'resolved.', '\n', '\n', 'First', 'Citizen:', '\n', 'First,', 'you', 'know', 'Caius', 'Marcius', 'is', 'chief', 'enemy', 'to', 'the', 'people.', '\n', '\n', 'All:', '\n', 'We', "know't,", 'we', "know't.", '\n', '\n', 'First', 'Citizen:', '\n', 'Let', 'us', 'kill', 'him,', 'and', "we'll", 'have', 'corn', 'at', 'our', 'own', 'price.', '\n', "Is't", 'a', 'verdict?', '\n', '\n', 'All:', '\n', 'No', 'more', 'talking', "on't;", 'let', 'it', 'be', 'done:', 'away,', 'away!', '\n', '\n', 'Second', 'Citizen:', '\n', 'One', 'word,', 'good', 'citizens.', '\n', '\n', 'First', 'Citizen:', '\n', 'We', 'are', 'accounted', 'poor', 'citizens,', 'the', 'patricians', 'good.', '\n', 'What', 'authority', 'surf

In [14]:
processed_text = (tokenization(split_newline(text)))

In [15]:
words = sorted(list(set(processed_text)))
print(words[-10:])
print(f'TOTAL words num: {len(words)}')

['▁you', '▁young', '▁younger', '▁youngest', '▁your', '▁yourself', '▁yourselves', '▁youth', '▁youthful', '▁zeal']
TOTAL words num: 9669


In [24]:
# create a mapping from characters to integers
stoi = { w:i for i,w in enumerate(words) }
itos = { i:w for i,w in enumerate(words) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ' '.join([itos[i] for i in l]).replace('▁', '') # decoder: take a list of integers, output a string

In [17]:
print(stoi)

{'\n': 0, '!': 1, '$': 2, "'": 3, ',': 4, '-': 5, '.': 6, ':': 7, ';': 8, '?': 9, 'A': 10, 'AB': 11, 'AE': 12, 'AG': 13, 'AGE': 14, 'AL': 15, 'ALL': 16, 'AM': 17, 'AMP': 18, 'AN': 19, 'ANA': 20, 'AND': 21, 'ANG': 22, 'ANT': 23, 'ARC': 24, 'ARD': 25, 'ARL': 26, 'ART': 27, 'AST': 28, 'AT': 29, 'ATA': 30, 'AU': 31, 'Ac': 32, 'Accept': 33, 'All': 34, 'An': 35, 'Arg': 36, 'Assist': 37, 'B': 38, 'BA': 39, 'BEL': 40, 'BER': 41, 'BET': 42, 'BO': 43, 'BR': 44, 'BRA': 45, 'BU': 46, 'BY': 47, 'Be': 48, 'Believe': 49, 'Blo': 50, 'Bo': 51, 'Br': 52, 'Breaking': 53, 'Breath': 54, 'Burn': 55, 'But': 56, 'By': 57, 'C': 58, 'CA': 59, 'CAL': 60, 'CAP': 61, 'CAR': 62, 'CAT': 63, 'CE': 64, 'CES': 65, 'CH': 66, 'CHI': 67, 'CHO': 68, 'CI': 69, 'CIO': 70, 'CIS': 71, 'CL': 72, 'CLA': 73, 'CLE': 74, 'COR': 75, 'CU': 76, 'CY': 77, 'Certainly': 78, 'Char': 79, 'Citizen': 80, 'Co': 81, 'Com': 82, 'Come': 83, 'Con': 84, 'Condition': 85, 'Correct': 86, 'Cousin': 87, 'Craft': 88, 'Cu': 89, 'D': 90, 'DA': 91, 'DEL': 

In [25]:
test_string = 'You are all resolved rather to die than to famish? \nHow are you today?'
print(split_newline(test_string))
print(tokenization(split_newline(test_string)))
encoding = encode(tokenization(split_newline(test_string)))
print(encoding)

['You', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish?', '\n', 'How', 'are', 'you', 'today?']
['▁You', '▁are', '▁all', '▁resolved', '▁rather', '▁to', '▁die', '▁than', '▁to', '▁', 'fa', 'm', 'ish', '?', '\n', '▁How', '▁are', '▁you', '▁today', '?']
[4041, 4295, 4191, 8095, 7937, 9134, 5422, 9037, 9134, 2545, 1000, 1557, 1361, 9, 0, 3179, 4295, 9659, 9135, 9]


In [26]:
decoding = decode(encoding)
print(decoding)

You are all resolved rather to die than to  fa m ish ? 
 How are you today ?


In [27]:
import torch

data = torch.tensor(encode(processed_text), dtype=torch.long)
print(data.shape, data.type)
print(data[:100])

torch.Size([354459]) <built-in method type of Tensor object at 0x000002135147D7B0>
tensor([3009, 2545,   80,    7,    0, 2682, 9475, 7773, 4257, 6117,    4, 6363,
        7025, 8635,    6,    0,    0, 2594,    7,    0, 2545,  314, 1818,    4,
        8635,    6,    0,    0, 3009, 2545,   80,    7,    0, 4041, 4295, 4191,
        8095, 7937, 9134, 5422, 9037, 9134, 2545, 1000, 1557, 1361,    9,    0,
           0, 2594,    7,    0, 3587, 2136,  912,    6, 8095,    6,    0,    0,
        3009, 2545,   80,    7,    0, 3009,    4, 9659, 6735, 2760, 2383, 3346,
        1387, 6656, 4861, 5690, 9134, 9044, 7522,    6,    0,    0, 2594,    7,
           0, 3972, 6735,    3, 2205,    4, 9475, 6735,    3, 2205,    6,    0,
           0, 3009, 2545,   80])


In [28]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]
print(f'The size of train data is : {len(train_data)}')
print(f'The size of val data is : {len(val_data)}')

The size of train data is : 319013
The size of val data is : 35446


In [29]:
block_size = 8
train_data[:block_size+1]

tensor([3009, 2545,   80,    7,    0, 2682, 9475, 7773, 4257])

In [30]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f'input: {context}, target: {target}')

input: tensor([3009]), target: 2545
input: tensor([3009, 2545]), target: 80
input: tensor([3009, 2545,   80]), target: 7
input: tensor([3009, 2545,   80,    7]), target: 0
input: tensor([3009, 2545,   80,    7,    0]), target: 2682
input: tensor([3009, 2545,   80,    7,    0, 2682]), target: 9475
input: tensor([3009, 2545,   80,    7,    0, 2682, 9475]), target: 7773
input: tensor([3009, 2545,   80,    7,    0, 2682, 9475, 7773]), target: 4257


In [31]:
torch.manual_seed(1337)
batch_size = 4 # How many independent sequences will be process in parallel?
block_size = 8 # What is the maximum context length for predictions?

In [32]:
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

In [33]:
batch_size = 4
block_size = 8

sindex = 0
eindex = batch_size * block_size
batch = data[sindex: eindex]
print("Unseprated batch:")
print(batch, "\n")
batch = batch.reshape((batch_size, block_size))
print(f"Sperated batch:")
print(batch)

Unseprated batch:
tensor([3009, 2545,   80,    7,    0, 2682, 9475, 7773, 4257, 6117,    4, 6363,
        7025, 8635,    6,    0,    0, 2594,    7,    0, 2545,  314, 1818,    4,
        8635,    6,    0,    0, 3009, 2545,   80,    7]) 

Sperated batch:
tensor([[3009, 2545,   80,    7,    0, 2682, 9475, 7773],
        [4257, 6117,    4, 6363, 7025, 8635,    6,    0],
        [   0, 2594,    7,    0, 2545,  314, 1818,    4],
        [8635,    6,    0,    0, 3009, 2545,   80,    7]])


In [34]:
def get_batch(batch_size, split):
    data = train_data if split == 'train' else val_data
    
    sindex = 0
    eindex = batch_size * block_size
    while eindex < (len(data) - block_size):
        # Extract batch_size * block_size tokens in the data
        xb = data[sindex: eindex]
        yb = data[sindex+1: eindex+1]
        # Reshape the batch by the shape (batch_size, block_size)
        xb = xb.reshape(batch_size, block_size)
        yb = yb.reshape(batch_size, block_size)
        # Update the indexes for extracting tokens sections
        temp = eindex
        eindex = eindex + block_size * batch_size
        sindex = temp
        yield xb, yb
    
    # For the last batch that cannot be batched as in the size (batch_size, block_size)
    # Maintain the 'block_size' dimension
    if eindex >= (len(data) - block_size):
        # The number of useable completed sample including 'block_size' elements
        num_sample = (len(data) - sindex) // block_size 
        if num_sample >= 1:
            xb = data[sindex: sindex + (num_sample * block_size)]
            yb = data[sindex+1: sindex + (num_sample * block_size)+1]
            xb = xb.reshape(num_sample, block_size)
            yb = yb.reshape(num_sample, block_size)
            yield xb, yb 

In [35]:
batch_size = 4
block_size = 8

num_batch = 0
for i, batch in enumerate(get_batch(batch_size, 'train')):
    xb, yb = batch
    if i < 1:
        print('inputs:')
        print(xb.shape)
        print(xb)
        print('targets:')
        print(yb.shape)
        print(yb)
    num_batch += 1

print(f'TOTAL number of batches: {num_batch}')

inputs:
torch.Size([4, 8])
tensor([[3009, 2545,   80,    7,    0, 2682, 9475, 7773],
        [4257, 6117,    4, 6363, 7025, 8635,    6,    0],
        [   0, 2594,    7,    0, 2545,  314, 1818,    4],
        [8635,    6,    0,    0, 3009, 2545,   80,    7]])
targets:
torch.Size([4, 8])
tensor([[2545,   80,    7,    0, 2682, 9475, 7773, 4257],
        [6117,    4, 6363, 7025, 8635,    6,    0,    0],
        [2594,    7,    0, 2545,  314, 1818,    4, 8635],
        [   6,    0,    0, 3009, 2545,   80,    7,    0]])
TOTAL number of batches: 9969


In [36]:
for b in range(batch_size): # batch dimension
    print(f'batch {b+1}/{batch_size}')
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")
    print()

batch 1/4
when input is [8412] the target: 4960
when input is [8412, 4960] the target: 8
when input is [8412, 4960, 8] the target: 4239
when input is [8412, 4960, 8, 4239] the target: 7300
when input is [8412, 4960, 8, 4239, 7300] the target: 4
when input is [8412, 4960, 8, 4239, 7300, 4] the target: 3510
when input is [8412, 4960, 8, 4239, 7300, 4, 3510] the target: 2332
when input is [8412, 4960, 8, 4239, 7300, 4, 3510, 2332] the target: 1716

batch 2/4
when input is [1716] the target: 4
when input is [1716, 4] the target: 8635
when input is [1716, 4, 8635] the target: 6
when input is [1716, 4, 8635, 6] the target: 0
when input is [1716, 4, 8635, 6, 0] the target: 3086
when input is [1716, 4, 8635, 6, 0, 3086] the target: 2545
when input is [1716, 4, 8635, 6, 0, 3086, 2545] the target: 1637
when input is [1716, 4, 8635, 6, 0, 3086, 2545, 1637] the target: 2039

batch 3/4
when input is [2039] the target: 4
when input is [2039, 4] the target: 3247
when input is [2039, 4, 3247] the targ