In [1]:
from nltk.tokenize import word_tokenize

In [2]:
text = 'I love this flavor! It\'s by far the best choice and my go-to whenever I go to the grocery store. \n I wish they would restock it more often though.'

In [3]:
word_tokens = word_tokenize(text)
print(word_tokens)

['I', 'love', 'this', 'flavor', '!', 'It', "'s", 'by', 'far', 'the', 'best', 'choice', 'and', 'my', 'go-to', 'whenever', 'I', 'go', 'to', 'the', 'grocery', 'store', '.', 'I', 'wish', 'they', 'would', 'restock', 'it', 'more', 'often', 'though', '.']


In [4]:
with open('../data/input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [5]:
text[:100]

'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou'

In [6]:
subtext = text.split(' ')[:100]
print(subtext)
for i, substring in enumerate(subtext):
    
    if '\n' in substring:
        chars = [c for c in substring]
        # print(chars)
        
        sindex = 0
        split_substring_list = []
        for j, char in enumerate(chars):
            
            if char == '\n':
                c_chars = ''.join(chars[sindex:j])
                if  c_chars != '':
                    split_substring_list.append(c_chars)
                    
                split_substring_list.append('\n')
                sindex = j + 1
                
        split_substring_list.append(''.join(chars[sindex:]))
        
        # print(split_substring_list)
        
        subtext[i] = split_substring_list
    else:
        subtext[i] = [substring]

print(subtext)

['First', 'Citizen:\nBefore', 'we', 'proceed', 'any', 'further,', 'hear', 'me', 'speak.\n\nAll:\nSpeak,', 'speak.\n\nFirst', 'Citizen:\nYou', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish?\n\nAll:\nResolved.', 'resolved.\n\nFirst', 'Citizen:\nFirst,', 'you', 'know', 'Caius', 'Marcius', 'is', 'chief', 'enemy', 'to', 'the', 'people.\n\nAll:\nWe', "know't,", 'we', "know't.\n\nFirst", 'Citizen:\nLet', 'us', 'kill', 'him,', 'and', "we'll", 'have', 'corn', 'at', 'our', 'own', "price.\nIs't", 'a', 'verdict?\n\nAll:\nNo', 'more', 'talking', "on't;", 'let', 'it', 'be', 'done:', 'away,', 'away!\n\nSecond', 'Citizen:\nOne', 'word,', 'good', 'citizens.\n\nFirst', 'Citizen:\nWe', 'are', 'accounted', 'poor', 'citizens,', 'the', 'patricians', 'good.\nWhat', 'authority', 'surfeits', 'on', 'would', 'relieve', 'us:', 'if', 'they\nwould', 'yield', 'us', 'but', 'the', 'superfluity,', 'while', 'it', 'were\nwholesome,', 'we', 'might', 'guess', 'they', 'relieved', 'us', 'humanely;\nb

In [7]:
subtext = [item for sublist in subtext for item in sublist]
print(subtext)

['First', 'Citizen:', '\n', 'Before', 'we', 'proceed', 'any', 'further,', 'hear', 'me', 'speak.', '\n', '\n', 'All:', '\n', 'Speak,', 'speak.', '\n', '\n', 'First', 'Citizen:', '\n', 'You', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish?', '\n', '\n', 'All:', '\n', 'Resolved.', 'resolved.', '\n', '\n', 'First', 'Citizen:', '\n', 'First,', 'you', 'know', 'Caius', 'Marcius', 'is', 'chief', 'enemy', 'to', 'the', 'people.', '\n', '\n', 'All:', '\n', 'We', "know't,", 'we', "know't.", '\n', '\n', 'First', 'Citizen:', '\n', 'Let', 'us', 'kill', 'him,', 'and', "we'll", 'have', 'corn', 'at', 'our', 'own', 'price.', '\n', "Is't", 'a', 'verdict?', '\n', '\n', 'All:', '\n', 'No', 'more', 'talking', "on't;", 'let', 'it', 'be', 'done:', 'away,', 'away!', '\n', '\n', 'Second', 'Citizen:', '\n', 'One', 'word,', 'good', 'citizens.', '\n', '\n', 'First', 'Citizen:', '\n', 'We', 'are', 'accounted', 'poor', 'citizens,', 'the', 'patricians', 'good.', '\n', 'What', 'authority', 'surf

In [8]:
for i, tokens in enumerate(subtext):
    if tokens == '\n':
        continue
    subtext[i] = word_tokenize(tokens)

print(subtext)

[['First'], ['Citizen', ':'], '\n', ['Before'], ['we'], ['proceed'], ['any'], ['further', ','], ['hear'], ['me'], ['speak', '.'], '\n', '\n', ['All', ':'], '\n', ['Speak', ','], ['speak', '.'], '\n', '\n', ['First'], ['Citizen', ':'], '\n', ['You'], ['are'], ['all'], ['resolved'], ['rather'], ['to'], ['die'], ['than'], ['to'], ['famish', '?'], '\n', '\n', ['All', ':'], '\n', ['Resolved', '.'], ['resolved', '.'], '\n', '\n', ['First'], ['Citizen', ':'], '\n', ['First', ','], ['you'], ['know'], ['Caius'], ['Marcius'], ['is'], ['chief'], ['enemy'], ['to'], ['the'], ['people', '.'], '\n', '\n', ['All', ':'], '\n', ['We'], ["know't", ','], ['we'], ["know't", '.'], '\n', '\n', ['First'], ['Citizen', ':'], '\n', ['Let'], ['us'], ['kill'], ['him', ','], ['and'], ['we', "'ll"], ['have'], ['corn'], ['at'], ['our'], ['own'], ['price', '.'], '\n', ["Is't"], ['a'], ['verdict', '?'], '\n', '\n', ['All', ':'], '\n', ['No'], ['more'], ['talking'], ['o', "n't", ';'], ['let'], ['it'], ['be'], ['done', '

In [9]:
subtext = [item for sublist in subtext for item in sublist]
print(subtext)

['First', 'Citizen', ':', '\n', 'Before', 'we', 'proceed', 'any', 'further', ',', 'hear', 'me', 'speak', '.', '\n', '\n', 'All', ':', '\n', 'Speak', ',', 'speak', '.', '\n', '\n', 'First', 'Citizen', ':', '\n', 'You', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish', '?', '\n', '\n', 'All', ':', '\n', 'Resolved', '.', 'resolved', '.', '\n', '\n', 'First', 'Citizen', ':', '\n', 'First', ',', 'you', 'know', 'Caius', 'Marcius', 'is', 'chief', 'enemy', 'to', 'the', 'people', '.', '\n', '\n', 'All', ':', '\n', 'We', "know't", ',', 'we', "know't", '.', '\n', '\n', 'First', 'Citizen', ':', '\n', 'Let', 'us', 'kill', 'him', ',', 'and', 'we', "'ll", 'have', 'corn', 'at', 'our', 'own', 'price', '.', '\n', "Is't", 'a', 'verdict', '?', '\n', '\n', 'All', ':', '\n', 'No', 'more', 'talking', 'o', "n't", ';', 'let', 'it', 'be', 'done', ':', 'away', ',', 'away', '!', '\n', '\n', 'Second', 'Citizen', ':', '\n', 'One', 'word', ',', 'good', 'citizens', '.', '\n', '\n', 'First', 'Ci

In [10]:
flatten = lambda l: [item for sublist in l for item in sublist]

In [36]:
def split_newline(text):
    text = text.split(' ')
    
    for i, substring in enumerate(text):
        # detect substring containing the newline symbol '\n'
        if '\n' in substring:
            # split the substring by characters
            chars = [c for c in substring]
            
            sindex = 0
            split_substring_list = []
            for j, char in enumerate(chars):
                # When meets a newline, append all previous chars as a substring ([sindex:j])
                if char == '\n':
                    c_chars = ''.join(chars[sindex:j])
                    if  c_chars != '':
                        split_substring_list.append(c_chars)
                    # Then added the '\n'
                    split_substring_list.append('\n')
                    # Update the sindex
                    sindex = j + 1
            # Added the rest of all chars as a substring
            split_substring_list.append(''.join(chars[sindex:]))
            # Replace the original string by a list of string
            text[i] = split_substring_list
        else:
            # warp other items as a list
            text[i] = [substring]
    
    # Flatten the 
    return flatten(text)

def tokenization(text):
    for i, token in enumerate(text):
        # print(token)
        if token == '\n':
            continue
        text[i] = word_tokenize(token)
    
    return flatten(text)

In [13]:
subtext = text[:1000]
# print(subtext)
split_newline_subtext = split_newline(subtext)
print(split_newline_subtext)
tokenization_subtext = tokenization(split_newline_subtext)
print(tokenization_subtext)

['First', 'Citizen:', '\n', 'Before', 'we', 'proceed', 'any', 'further,', 'hear', 'me', 'speak.', '\n', '\n', 'All:', '\n', 'Speak,', 'speak.', '\n', '\n', 'First', 'Citizen:', '\n', 'You', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish?', '\n', '\n', 'All:', '\n', 'Resolved.', 'resolved.', '\n', '\n', 'First', 'Citizen:', '\n', 'First,', 'you', 'know', 'Caius', 'Marcius', 'is', 'chief', 'enemy', 'to', 'the', 'people.', '\n', '\n', 'All:', '\n', 'We', "know't,", 'we', "know't.", '\n', '\n', 'First', 'Citizen:', '\n', 'Let', 'us', 'kill', 'him,', 'and', "we'll", 'have', 'corn', 'at', 'our', 'own', 'price.', '\n', "Is't", 'a', 'verdict?', '\n', '\n', 'All:', '\n', 'No', 'more', 'talking', "on't;", 'let', 'it', 'be', 'done:', 'away,', 'away!', '\n', '\n', 'Second', 'Citizen:', '\n', 'One', 'word,', 'good', 'citizens.', '\n', '\n', 'First', 'Citizen:', '\n', 'We', 'are', 'accounted', 'poor', 'citizens,', 'the', 'patricians', 'good.', '\n', 'What', 'authority', 'surf

In [18]:
processed_text = (tokenization(split_newline(text)))

In [19]:
words = sorted(list(set(processed_text)))
print(words[-10:])
print(f'TOTAL words num: {len(words)}')

['your', 'yours', 'yourself', 'yourselves', 'youth', 'youthful', 'zeal', 'zealous', 'zenith', 'zodiacs']
TOTAL words num: 14207


In [20]:
# create a mapping from characters to integers
stoi = { w:i for i,w in enumerate(words) }
itos = { i:w for i,w in enumerate(words) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ' '.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

In [22]:
print(stoi)

{'\n': 0, '!': 1, '$': 2, '&': 3, "'": 4, "'Alas": 5, "'Alla": 6, "'An": 7, "'Ay": 8, "'Be": 9, "'Beseech": 10, "'Bless": 11, "'Bove": 12, "'Brutus": 13, "'By": 14, "'Charge": 15, "'Citizens": 16, "'Clarence": 17, "'Come": 18, "'Commend": 19, "'Con": 20, "'Content": 21, "'Coriolanus": 22, "'Courage": 23, "'Cucullus": 24, "'Dear": 25, "'Death": 26, "'Deny": 27, "'Do": 28, "'Fair": 29, "'Faith": 30, "'Farewell": 31, "'Fine": 32, "'Fore": 33, "'Forgive": 34, "'Frets": 35, "'Gainst": 36, "'Go": 37, "'God": 38, "'Good": 39, "'Have": 40, "'He": 41, "'Heart": 42, "'Hell": 43, "'Hic": 44, "'Hold": 45, "'Is": 46, "'It": 47, "'Jack": 48, "'Jesu": 49, "'King": 50, "'Lo": 51, "'Look": 52, "'Madam": 53, "'Margaret": 54, "'My": 55, "'Now": 56, "'Pardon": 57, "'Patricians": 58, "'Peace": 59, "'Priami": 60, "'Proud": 61, "'Redime": 62, "'Remember": 63, "'Retire": 64, "'Rise": 65, "'Romeo": 66, "'Saint": 67, "'Save": 68, "'Scape": 69, "'Sdeath": 70, "'Shall": 71, "'She": 72, "'Sicilia": 73, "'Sicinius"

In [21]:
test_string = 'You are all resolved rather to die than to famish? \nHow are you today?'
print(split_newline(test_string))
print(tokenization(split_newline(test_string)))
encoding = encode(tokenization(split_newline(test_string)))
print(encoding)

['You', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish?', '\n', 'How', 'are', 'you', 'today?']
['You', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish', '?', '\n', 'How', 'are', 'you', 'today', '?']
[3045, 3501, 3314, 10977, 10718, 12915, 5701, 12727, 12915, 6502, 223, 0, 1455, 3501, 14188, 12924, 223]


In [23]:
print(decode(encoding))

You are all resolved rather to die than to famish ? 
 How are you today ?


In [24]:
import torch

data = torch.tensor(encode(processed_text), dtype=torch.long)
print(data.shape, data.type)
print(data[:100])

torch.Size([294798]) <built-in method type of Tensor object at 0x0000018806EAD530>
tensor([ 1149,   706,   221,     0,   480, 13779, 10409,  3429,  7046,   217,
         7569,  8941, 12002,   219,     0,     0,   321,   221,     0,  2512,
          217, 12002,   219,     0,     0,  1149,   706,   221,     0,  3045,
         3501,  3314, 10977, 10718, 12915,  5701, 12727, 12915,  6502,   223,
            0,     0,   321,   221,     0,  2248,   219, 10977,   219,     0,
            0,  1149,   706,   221,     0,  1149,   217, 14188,  8357,   638,
         1762,  8190,  4665,  6225, 12915, 12738,  9972,   219,     0,     0,
          321,   221,     0,  2911,  8359,   217, 13779,  8359,   219,     0,
            0,  1149,   706,   221,     0,  1672, 13485,  8298,  7701,   217,
         3401, 13779,   161,  7533,  5130,  3584,  9701,  9773, 10368,   219])


In [25]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]
print(f'The size of train data is : {len(train_data)}')
print(f'The size of val data is : {len(val_data)}')

The size of train data is : 265318
The size of val data is : 29480


In [26]:
block_size = 8
train_data[:block_size+1]

tensor([ 1149,   706,   221,     0,   480, 13779, 10409,  3429,  7046])

In [27]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f'input: {context}, target: {target}')

input: tensor([1149]), target: 706
input: tensor([1149,  706]), target: 221
input: tensor([1149,  706,  221]), target: 0
input: tensor([1149,  706,  221,    0]), target: 480
input: tensor([1149,  706,  221,    0,  480]), target: 13779
input: tensor([ 1149,   706,   221,     0,   480, 13779]), target: 10409
input: tensor([ 1149,   706,   221,     0,   480, 13779, 10409]), target: 3429
input: tensor([ 1149,   706,   221,     0,   480, 13779, 10409,  3429]), target: 7046


In [28]:
torch.manual_seed(1337)
batch_size = 4 # How many independent sequences will be process in parallel?
block_size = 8 # What is the maximum context length for predictions?

In [29]:
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

In [30]:
batch_size = 4
block_size = 8

sindex = 0
eindex = batch_size * block_size
batch = data[sindex: eindex]
print("Unseprated batch:")
print(batch, "\n")
batch = batch.reshape((batch_size, block_size))
print(f"Sperated batch:")
print(batch)

Unseprated batch:
tensor([ 1149,   706,   221,     0,   480, 13779, 10409,  3429,  7046,   217,
         7569,  8941, 12002,   219,     0,     0,   321,   221,     0,  2512,
          217, 12002,   219,     0,     0,  1149,   706,   221,     0,  3045,
         3501,  3314]) 

Sperated batch:
tensor([[ 1149,   706,   221,     0,   480, 13779, 10409,  3429],
        [ 7046,   217,  7569,  8941, 12002,   219,     0,     0],
        [  321,   221,     0,  2512,   217, 12002,   219,     0],
        [    0,  1149,   706,   221,     0,  3045,  3501,  3314]])


In [31]:
def get_batch(batch_size, split):
    data = train_data if split == 'train' else val_data
    
    sindex = 0
    eindex = batch_size * block_size
    while eindex < (len(data) - block_size):
        # Extract batch_size * block_size tokens in the data
        xb = data[sindex: eindex]
        yb = data[sindex+1: eindex+1]
        # Reshape the batch by the shape (batch_size, block_size)
        xb = xb.reshape(batch_size, block_size)
        yb = yb.reshape(batch_size, block_size)
        # Update the indexes for extracting tokens sections
        temp = eindex
        eindex = eindex + block_size * batch_size
        sindex = temp
        yield xb, yb
    
    # For the last batch that cannot be batched as in the size (batch_size, block_size)
    # Maintain the 'block_size' dimension
    if eindex >= (len(data) - block_size):
        # The number of useable completed sample including 'block_size' elements
        num_sample = (len(data) - sindex) // block_size 
        if num_sample >= 1:
            xb = data[sindex: sindex + (num_sample * block_size)]
            yb = data[sindex+1: sindex + (num_sample * block_size)+1]
            xb = xb.reshape(num_sample, block_size)
            yb = yb.reshape(num_sample, block_size)
            yield xb, yb 

In [34]:
batch_size = 4
block_size = 8

num_batch = 0
for i, batch in enumerate(get_batch(batch_size, 'train')):
    xb, yb = batch
    if i < 1:
        print('inputs:')
        print(xb.shape)
        print(xb)
        print('targets:')
        print(yb.shape)
        print(yb)
    num_batch += 1

print(f'TOTAL number of batches: {num_batch}')

inputs:
torch.Size([4, 8])
tensor([[ 1149,   706,   221,     0,   480, 13779, 10409,  3429],
        [ 7046,   217,  7569,  8941, 12002,   219,     0,     0],
        [  321,   221,     0,  2512,   217, 12002,   219,     0],
        [    0,  1149,   706,   221,     0,  3045,  3501,  3314]])
targets:
torch.Size([4, 8])
tensor([[  706,   221,     0,   480, 13779, 10409,  3429,  7046],
        [  217,  7569,  8941, 12002,   219,     0,     0,   321],
        [  221,     0,  2512,   217, 12002,   219,     0,     0],
        [ 1149,   706,   221,     0,  3045,  3501,  3314, 10977]])
TOTAL number of batches: 8291


In [35]:
for b in range(batch_size): # batch dimension
    print(f'batch {b+1}/{batch_size}')
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")
    print()

batch 1/4
when input is [9641] the target: 7435
when input is [9641, 7435] the target: 9602
when input is [9641, 7435, 9602] the target: 9317
when input is [9641, 7435, 9602, 9317] the target: 8418
when input is [9641, 7435, 9602, 9317, 8418] the target: 217
when input is [9641, 7435, 9602, 9317, 8418, 217] the target: 0
when input is [9641, 7435, 9602, 9317, 8418, 217, 0] the target: 348
when input is [9641, 7435, 9602, 9317, 8418, 217, 0, 348] the target: 7977

batch 2/4
when input is [7977] the target: 10238
when input is [7977, 10238] the target: 13164
when input is [7977, 10238, 13164] the target: 12803
when input is [7977, 10238, 13164, 12803] the target: 5311
when input is [7977, 10238, 13164, 12803, 5311] the target: 219
when input is [7977, 10238, 13164, 12803, 5311, 219] the target: 0
when input is [7977, 10238, 13164, 12803, 5311, 219, 0] the target: 0
when input is [7977, 10238, 13164, 12803, 5311, 219, 0, 0] the target: 1992

batch 3/4
when input is [1992] the target: 221
